task_app/config/routes.rb
Rails.application.routes.draw do
  get 'schedules/index' => "schedules#index"
  resources:schedules
end

task_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

task_app/app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence: true,length: { maximum: 5 }
  validates :start, presence: true
  validates :close, presence: true
  after_validation :start_end_check
  validates :memo, length: { maximum: 200 }
  
  def start_end_check
    return if start.presence && close.presence && self.start <= self.close
    errors.add(:close, "は開始日以降の日付で登録ください。") 
  end
  
end

task_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

task_app/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  
  def index
    @schedules = Schedule.all
  end
  
  def new
	  @schedule = Schedule.new
  end
  
  def create
    @schedule = Schedule.new(params.require(:schedule).permit(:title, :start, :close, :allday, :memo))
    @schedule.errors.any?
    @schedule.valid?

    if @schedule.save
      flash[:notice] = "スケジュールを新規登録しました"
      redirect_to :schedules
    else
      flash.now[:notice] = "ERROR! 登録できませんでした"
      render "new"
    end
  end
  
  def show
    @schedule = Schedule.find(params[:id])
  end
  
  def edit
    @schedule = Schedule.find(params[:id])
    @schedule.errors.any?
    @schedule.valid?
  end
  
  def update
    @schedule = Schedule.find(params[:id])
    if @schedule.update(params.require(:schedule).permit(:title, :start, :close, :allday, :memo))
      flash[:notice] = "スケジュールを更新しました"
      redirect_to :schedules
    else
      flash.now[:notice] = "ERROR! 更新できませんでした"
      render "edit"
    end
  end
  
  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy
    flash[:notice] = "スケジュールを削除しました"
    redirect_to :schedules
  end
  
end

task_app/app/helpers/application_helper.rb
module ApplicationHelper
end

task_app/app/helpers/schedules_helper.rb
module SchedulesHelper
end

task_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  
  <body>
    <header>
      Ruby on Rails スケジュール管理アプリ
    </header>
    
    <main>
    <%= yield %>
    </main>
    
    <footer>
      現在の日時：<%= Date.current.strftime('%Y年 %m月 %d日') %> スケジュールの合計：<%= Schedule.count %>
    </footer>
  </body>
</html>

task_app/app/views/schedules/edit.html.erb
<h3><%= image_tag 'techou_open.png', class: 'img' %> スケジュール編集</h3>

<% if flash.now[:notice] %>
      <p class="notice"><%= flash.now[:notice] %></p>
      <%= render 'shared/error_form', locals: { schedule: @schedule } %>
<% end %>


<%= form_with model: @schedule do |f| %>
      <table>
        <tr>
          <th><%= f.label :title ,"タイトル" %> <span class="f_column">※必須</th>
          <td><%= f.text_field :title, class: "form_check" %></td>
        </tr>
        <tr>
          <th><%= f.label :start ,"開始日" %> <span class="f_column">※必須</span></th>
          <td><%= f.date_field :start, class: "form_check"  %></td>
        </tr>
        <tr>
          <th><%= f.label :close ,"終了日" %> <span class="f_column">※必須</th>
          <td><%= f.date_field :close, class: "form_check"  %></td>
        </tr>
        <tr>
          <th><%= f.label :allday ,"終日" %></th>
          <td><%= f.check_box :allday, {:checked => false}, true, false %><br>終日の場合はチェック</p></td>
        </tr>
        <tr>
          <th><%= f.label :memo ,"スケジュールメモ" %></th>
          <td><%= f.text_area :memo, class: "form_check"  %></td>
        </tr>
      </table>
      <div>
          <p><%= f.submit "編集を完了する", class: "end_btn" %></p>
          <p><%= link_to "スケジュール一覧に戻る", schedules_path, class:"index-link" %></p>
      </div>
    <% end %>

task_app/app/views/schedules/index.html.erb
<h3><%= image_tag 'pen_enpitsu_mark.png', class: 'img' %> スケジュール一覧</h3>

<% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
<% end %>
 
    <table>
      <thead>
        <tr>
          <th>id</th>
          <th>タイトル</th>
          <th>開始日</th>
          <th>終了日</th>
          <th>終日</th>
          <th>スケジュール更新日時</th>
          <th>確認</th>
          <th>編集</th>
          <th>削除</th>
        </tr>
      </thead>
      
      <tbody>
        <% @schedules.each do |schedule| %>
          <tr>
            <td><%= schedule.id %></td>
            <td><%= schedule.title %></td>  
            <td><%= schedule.start.strftime("%Y年 %m月 %d日") %></td>
            <td><%= schedule.close.strftime("%Y年 %m月 %d日") %></td>
            <td><% if schedule.allday == true %>
                <string>○</string>
                <% end %>
            </td>
            <td><%= schedule.updated_at.to_s(:datetime_jp) %></td>
            <td><%= link_to "確認", schedule %></td>
            <td><%= link_to "編集", [:edit, schedule] %></td>
            <td><%= link_to "削除", schedule, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
    <p class="btn btn--orange btn--border-solid"><%= link_to "スケジュール新規登録", :new_schedule, class: "new-link" %></p>

task_app/app/views/schedules/new.html.erb
<h3><%= image_tag 'techou.png', class: 'img' %> スケジュール新規追加</h3>

<% if flash.now[:notice] %>
      <p class="notice"><%= flash.now[:notice] %></p>
      <%= render 'shared/error_form', locals: { schedule: @schedule } %>
<% end %>


<%= form_with model: @schedule do |f| %>
      <table>
        <tr>
          <th><%= f.label :title ,"タイトル" %> <span class="f_column">※必須</th>
          <td><%= f.text_field :title, class: "form_check" %></td>
        </tr>
        <tr>
          <th><%= f.label :start ,"開始日" %> <span class="f_column">※必須</span></th>
          <td><%= f.date_field :start, class: "form_check"  %></td>
        </tr>
        <tr>
          <th><%= f.label :close ,"終了日" %> <span class="f_column">※必須</th>
          <td><%= f.date_field :close, class: "form_check"  %></td>
        </tr>
        <tr>
          <th><%= f.label :allday ,"終日" %></th>
          <td><%= f.check_box :allday, {:checked => false}, true, false %><br>終日の場合はチェック</p></td>
        </tr>
        <tr>
          <th><%= f.label :memo ,"スケジュールメモ" %></th>
          <td><%= f.text_area :memo, class: "form_check"  %></td>
        </tr>
      </table>
        <p><%= f.submit "登録完了する", class: "end_btn" %></p>
        <p><%= link_to "スケジュール一覧に戻る", schedules_path, class: "index-link" %></p>
<% end %>

task_app/app/views/schedules/show.html.erb
<H2><%= image_tag 'smartphone_cover_techou.png', class: 'img' %> スケジュール詳細</H2>

    <table>
        <tr>
            <th>タイトル</th>
            <td><%= @schedule.title %></td>
        </tr>
        <tr>
            <th>開始日</th><td><%= @schedule.start %></td>
        </tr>
        <tr>
            <th>終了日</th><td><%= @schedule.close %></td>
        </tr>
        <tr>
            <th>終日</th>
            <td>
                <% if @schedule.allday == true %>
                <string>○</string>
                <% end %>
            </td>
        </tr>           
        <tr>
            <th>スケジュールメモ</th><td><%= @schedule.memo %>
        </td>
        </tr>   
    </table>

<p><%= link_to "スケジュール一覧に戻る", schedules_path, class: "index-link" %></p>

task_app/app/views/shared/_error_form.html.erb
<% if @schedule.errors.any? %>
  <div class = "alert">
    <ul>
      <% @schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>